[package]
name = "libq3vm-sys"
version = "0.1.2"
authors = ["Raffael Zica <raffael@pixeltastic.de>"]
build = "build.rs"

[dependencies]
lazy_static = "1"
log = "0.4"

[build-dependencies]
cc = "1"
bindgen = "0.26"
crc = "1.8"
commandspec = "0.10"
maplit = "1.0"