[package]
name = "helloq3"
version = "0.1.0"
authors = ["Raffael Zica <raffael@pixeltastic.de>"]

[dependencies]
rq3vm = { path = "../.." }
log = "0.4"
pretty_env_logger = "0.2"
strfmt = "0.1"
regex = "1"
enum-primitive-derive = "0.1"
num-traits = "0.2"
lazy_static = "1"